apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: easyshop-routes
  namespace: easyshop
spec:
  parentRefs:
  - name: easyshop-gateway
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: easyshop-service
      port: 80
  